### ISSUE TITLE
User Interaction

### ISSUE THREAD

**Issue by halfpintutopia** [halfpintutopia/learn-code-share-repeat#12]
### EPIC: #16 

***

### USER STORY

As a **user**, I want to **follow others and receive notifications** so I can **engage with the community**.

***

### ACCEPTANCE CRITERIA

- [ ] User can follow others and receive notifications
- [ ] Follows and notifications are saved and displayed

***

### TASKS

- [ ] Implement Django models for follows and notifications
- [ ] Create follow and notification components in React
- [ ] Connect components to Django backend
- [ ] Write unit tests for follows and notifications
- [ ] Test follows and notifications manually

***

### DEPENDENCIES
**EPIC:** #15
