### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by halfpintutopia** [halfpintutopia/learn-code-share-repeat#27]
### EPIC: #3 

***

### USER STORY

As a **user**, I want to **reset my password** so I can **regain access to my account** if I forget my password.

***

### ACCEPTANCE CRITERIA

- [ ] User can request reset
- [ ] User receives an email with a password reset link
- [ ] User can reset passwords using a link

***

### TASKS

- [ ] Implement Django password reset
- [ ] Create a password reset form in React
- [ ] Connect form to Django backend
- [ ] Write unit tests for password reset
- [ ] Test password reset form manually

***

### DEPENDENCIES
**EPIC:** #2
