### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by halfpintutopia** [halfpintutopia/learn-code-share-repeat#6]
### EPIC: #2 

***

### USER STORY

As a **user**, I want to **register** so that I can **create an account**

***

### ACCEPTANCE CRITERIA

- [x] User can register with email and password
- [x] User receives confirmation email

***

### TASKS

- [x] Implement Django User model
- [x] Create a registration form in React
- [x] Connect form to Django backend
- [x] Write unit tests for registration
- [x] Test registration form manually

***

### DEPENDENCIES
**EPIC:** None
