### ISSUE TITLE
Video Management

### ISSUE THREAD

**Issue by halfpintutopia** [halfpintutopia/learn-code-share-repeat#8]
### EPIC: #4 

***

### USER STORY

As a **user**, I want to **upload videos** to **share my content**.

***

### ACCEPTANCE CRITERIA

- [ ] User can upload video with title and description
- [ ] Uploaded video is saved in the user's account

***

### TASKS

- [x] Implement Django model for videos
- [ ] Create a video upload form in React
- [ ] Connect form to Django backend
- [x] Write unit tests for video upload
- [ ] Test video upload form manually

***

### DEPENDENCIES
**EPIC:** #3
