### ISSUE TITLE
Video Management

### ISSUE THREAD

**Issue by halfpintutopia** [halfpintutopia/learn-code-share-repeat#9]
### EPIC: #5 

***

### USER STORY

As a **user**, I want to **view videos** so that I can **watch content**.

***

### ACCEPTANCE CRITERIA

- [ ] User can view videos
- [ ] Video display includes title and description

***

### TASKS

- [ ] Create a video display component in React
- [ ] Connect component to Django backend
- [ ] Write unit tests for video display
- [ ] Test video display manually

***

### DEPENDENCIES
**EPIC:** #4
